name: cyclop
description: Cyclop is a flutter color palette with an optional eyedropper tool on mobile and desktop.
version: 0.2.4+3
homepage: https://github.com/rxlabz/cyclop

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  image: ^2.1.1
  quiver: ^2.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/grid.png
